#include <builtins.h>

char const *	builtin_triggers[] =	{
	"abnormal",
	"abo?rt",
	"access beyond",
	"asked fo",
	"bcm5709",
	"blocked for more",
	"becomes",
	"bond",
	"call trace:",
	"clocksource",
	"conflict",
	"crs",
	"css",
	"device-mappe",
	"(de)?bug",
	"dlm",
	"disagrees.*symbol.*",
	"don\'t",
	"end_request",
	"erro",
	"fail",
	"fenc(e,ing)",
	"fsck",
	"\bh[au]ng",
	"illegal:",
	"init:",
	"invalid:",
	"i?scsi",
	"kdump:?",
	"kill",
	"link",
	"linux version",
	"lpfc",
	"multipathd",
	"netdev",
	"nfs:.*not responding",
	"nfsd:",
	"no space left",
	"not supported",
	"\bnmi",
	"o2",
	"ocfs",
	"only",
	"oom",
	"oops",
	"out.*of.*memory",
	"own address",
	"panic",
	"please",
	"page allocation failure",
	"power states",
	"qla.*loop",
	"rds/(ib)?",
	"read-?only",
	"register(ed)?",
	"require",
	"restart",
	"segfault",
	"selinux",
	"signal",
	"sysrq.*:",
	"taint",
	"terminated",
	"time-?out",
	"unable",
	"unknown symbol.*",
	"unsupported",
	"vfs:",
	"warning",
	"watchdog"
};
unsigned	nBuiltin_triggers = sizeof(builtin_triggers) / sizeof( builtin_triggers[0] );
