.TH VLM-TOOL "1" "February 2012" "Tommy.Reynolds@MegaCoder.com" "User Commands"
.SH NAME
vlm-tool \- coalesce /var/log/messages from different hosts and filter
.SH SYNOPSIS
.B vlm-tool
[\fI-a\fR re]
[\fI-A\fR FILE]
[\fI-c\fR]
[\fI-g\fR]
[\fI-G\fR FILE]
[\fI-i\fR re]
[\fI-I\fR FILE]
[\fI-l\fR]
[\fI-m\fR]
[\fI-n\fR]
[\fI-N\fR]
[\fI-o\fR FILE]
[\fI-r\fR]
[\fI-s\fR]
[\fI-t\fR THUMB]
[\fI-v\fR]
[\fI-X\fR]
[\fI-y\fR year]
[\fI/var/log/messages\fR]...
.SH DESCRIPTION
.PP
Reads the named
\fI/var/log/messages\fR
files, merges them by the timestamp, and then filters the result.
Recognizes and automatically expands \fB.bz2\fR and \fB.gz\fR compressed files.
If no files are named, then the local
\fI/var/log/messages\fR*
files are read by default.
This will require superuser privilege, so don't be surprised.
.PP
Program output is written to stdout by default; change this using the \fI-o\fR option.
.PP
With no selection options, \fIvlm-tool\fR will compare each message file entry
against a built-in list of trigger words, which are really just python regular expressions.
Additional trigger words can be added using the \fI-a\fR option.
Triggers can be bulk loaded from a file, one per line, using the \fI-b\fR option.
.PP
All matching is case insensitive.
.PP
Avoid loading the built-in triggers by using the \fI-n\fR option.
.PP
Lines containing one or more trigger word may be \fImarked\fR.
When output, the line will be prefixed by the \fIthumb\fR, which is a minus (-) by default.
Use the \fI-r\fR option to identify which trigger was matched against the line.
.PP
The output may be colorized by using the \fI-c\fR option.
Non-matched parts of the line are written normally;
the matching segment is highlighted using a bright red color.
ANSI color escapes are used for this.
Currently, the colors may not be changed.
As an aide to visually grouping related entries together, host names are
highlighted using separate colors.
Host name colors are recycled as needed.
.SH POSTPROCESSING
.PP
When any of the marking options (\fI-c\fR or \fI-m\fR) are used, all of the
input lines are kept.
A special post-processing phase is then enabled.
\fIVLM-TOOL\fR attempts to highlight interesting stanzas of lines.
What stanzas the tool considers to be interesting cannot be changed from the
command line.
.SH OPTIONS
.IP "-a re" 10em
Add the regular expression \fBre\fR to the list of triggers.
.IP "-A FILE" 10em
Bulk-load a list of trigger regular expressions from \fBFILE\fR, one per line.
.IP "-c" 10em
Colorize the matching text in each entry, using ANSI escape codes.
Implies \fI-m\fP switch.
.IP "-g" 10em
Turns on gap analysis, which marks the first message after a selectale time period.
.IP "-G secs" 10em
Minimal interval between to log messages before a gap is declared.  Defaults to 10 minutes.
.IP "-i re" 10em
Totally ignore incoming lines matching regular expression \fBre\fR.
.IP "-I FILE" 10em
Bulk-load a list of ignored regular expressions from \fBFILE\fR, one per line.
.IP "-l" 10em
List the current trigger set.
.IP "-m" 10em
Mark those lines matching one or more triggers by prepending the \fBTHUMB\fR
to the output line.
An equivalent number of spaces are used for non-matching entries.
.IP "-n" 10em
Do not populate the built-in triggers.
Triggers specified on the command line take precedence over built-in patterns.
.IP "-N" 10em
Number the output lines, similar to piping the output through the
.BR nl( 1 )
utility.
These output line numbers bear no relationship to the input sequence.
.IP "-o FILE" 10em
Write output to \fBFILE\fR instead of to the standard output.
.IP "-r" 10em
Show the matching trigger rule which caused the entry to be marked.
Implies \fI-m\fP switch.
.IP "-s" 10em
Display internal statistics.
.IP "-t thumb" 10em
Use \fBthumb\fP to mark matching entries instead of the default of \fB-\fP (minus).
The default setting makes it easy to search for matches in less(1):
\fB/^-\fP will do it.
.IP "-v" 10em
Display program name, version, and then exit.
.IP "-X" 10em
Trust me.  You do not want to know...
.IP "-y year" 10em
Log file entries lack the year specifier.
By default, the current year is used; we need this to correctly calculate leap dates.
.SH VERSION
The information here relates to version 2.0.9; your mileage may vary.
.SH AUTHOR
Tommy Reynolds <Tommy.Reynolds@MegaCoder.com>
.SH COPYRIGHT
Copyright \(co 2012 Tommy Reynolds
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Read about egrep(1) regular expressions if the matches surprise you.
.SH BUGS
.PP
All of the \fI/var/log/messages\fR files must be from the same year.
The tool does not handle lines from differing years very well.
If could probably be modified to treat a timestamp of later in the year than
the current time as being from the prior year, but this complicates things and
slows things down as well.
.SH EXAMPLES
.IP "\f(CR$ sudo vlm-tool\fP" 20m
Output only those lines in \fI/var/log/messages*\fP which match one or
more trigger patterns.
.IP "\f(CR$ vlm-tool -a foo messages\fP" 20m
Output only entries matching the built-in patterns and \fIfoo\fP.
.IP "\f(CR$ vlm-tool -o results messages\fP" 20m
Write matching lines into \fBresults\fP instead of to the standard output.
.IP "\f(CR$ sudo vlm-tool -m\fP" 20m
Ingest all the entries in the \fI/var/log/messages*\fP files.
Output all lines, marking lines matching one or more triggers using the
\fITHUMB\fP.
Performs the postprocessing phase to highlight interesting stanzas.
The default \fITHUMB\fP is a minus (-).
.IP "\f(CR$ vlm-tool -mr -o myfile foo foo.1.gz\fP" 20m
Ingest all entries in \fIfoo\fP and \fIfoo.1.gz\fP and sort by timestamp.
Prefix any line matching one or more triggers with the \fITHUMB\fP and the
text of the matching rule.
Performs the postprocessing phase to highlight interesting stanzas.
.IP "\f(CR$ vlm-tool -c messages | less\fP" 20m
Ingest all entries from \fBmessages\fP and output all lines,
highlighting lines with one or more matches.
Performs the postprocessing phase to highlight interesting stanzas.
.IP "\f(CR$ vlm-tool -n -a ocfs2 messages\fP" 20m
Output only those entries matching the trigger of \fIocfs2\fP.
Note the use of the \fI-n\fP option to disable loading of the built-in rules.
